version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: gaussdb_dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=latam_store_db
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: